OPENAI_API_KEY =  "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"
ADMIN_PASSWORD = "Lawrence"

DB_USER = "your_username"
DB_PASSWORD = "your_password"
DB_HOST = "host_of_your_database"
DB_PORT = "26257" # default port for CockroachDB
DB_NAME = "your_database_name"

DB_CONNECTION = "postgresql://chergpt-basic:kGls8yQyT1-Rr51eykrhHA@song-piglet-7893.8nk.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full"